### ISSUE TITLE
Interação com o ViaCEP Client

### ISSUE THREAD

**Issue by gilberto-torrezan** [parg-programador/ViaCEP#1]
Olá @parg-programador,

Sou o criador do primeiro wrapper do ViaCEP para Java, o [ViaCEP Client](https://github.com/gilberto-torrezan/viacep), que tem utilização em GWT, Android e Java SE (inclusive em aplicações Swing/AWT).

Gostaria de saber se o seu projeto contempla alguma funcionalidade que falta no ViaCEP Client, ou algo que poderia melhorar. Acredito que focando os esforços em uma única biblioteca completa fique melhor para a comunidade do que várias bibliotecas isoladas.

Fico a disposição.

**Comment by parg-programador** [comment]
Olá @gilberto-torrezan,

O que você disse é verdade, mas eu cheguei a usar a sua classe no projeto aqui da empresa onde eu trabalho que se baseia em um sistema web em JSP e um App Android, porém tive problemas de memória no projeto principal que é em JSP e que para a empresa já é uma fortuna a hospedagem em Java.

Então acabou que eu tive que criar esse solução mais simples para e funciona-se em todas as plataformas que a empresa trabalha, como a classe funcionou perfeitamente e teve o desempenho que era necessário resolvi compartilha-la com a comunidade.

Inclusive estou pesando em criar um novo projeto usando parte do que criamos aqui na empresa onde que o CEP consultado no ViaCEP é automáticamente cadastrado em uma base de dados caso ele não exista e a cada seis meses ele expira e é consultado novamente no ViaCEP e é atualizado na base da dados, evitando consultas repetitivas e maximizando a velocidade da consulta para o usuário final (no caso dos CEP`s que estão cadastrados na base de dados).

Mas é somente uma ideia, caso você tenha alguma ideia fico feliz em ajudar.

Eu estudei muito o seu projeto e ele tem muito mais funções e recursos do que o meu, mas, existe casos em que os recursos são escassos e precisamos nos adaptar as necessidades e possiblidades da empresa ou cliente.

Fico feliz pelo seu feedback e estou a disposição.

**Comment by parg-programador** [comment]
Somente completando, o seu projeto **ViaCEP Client** tem muito mais opções do que o meu, mas que para as necessidades atuais da minha empresa e provavelmente de alguns mebros da comunidade são desnecessárias, por isso que voltei o meu projeto para ser simples e direto principalmente para economizar memória da JVM para ambientes Java Web.

Acho interessante a possibilidade de escolha, onde cada um vai avaliar as sua necessidades e recursos disponiveis e escolher.

Em minha visão que tem um projeto para grandes empresas provavelmente vai escolher o **ViaCEP Client**, mas quem tem menos necessidades do que isso provalmente vai escolher a opção mais simples.

**Comment by gilberto-torrezan** [comment]
Olá novamente,

Fiquei curioso agora sobre o uso de memória. Em meus benchmarks, rodando com heap minúscula (-Xms16m -Xmx32m), o ViaCEP Client performa bem sem nenhum problema. Inclusive é usado em Android, que convenhamos, não possui a memória e os recursos de uma VM server.

Você teve algum problema específico de leak ou uso de memória excessivo? Qual exatamente o ambiente? Quais chamadas foram utilizadas? Por favor se possível me envie os seus achados para que eu possa evitar eventuais problemas com a lib - e eventualmente abrir um bug no [issue tracker](https://github.com/gilberto-torrezan/viacep/issues) do projeto ;-)

Fiz um projeto de benchmark para fazer o profiling do uso de memória, tanto com o ViaCEP Client quanto com o seu projeto, mas não pude executar o seu pois ele requer Java 8 (meu ambiente está restrito a Java 7, por diversos fatores - o ViaCEP Client requer Java 6).

Código simples de benchmark:
```java
public static void main(String[] args) {
		System.out.println("Starting BenchmarkViaCEPClient...");
		
		ViaCEPClient client = new ViaCEPClient();
		
		String[] ceps = new String[]{"20930-040", "01311-000", "30140-010", "40026-040", "90010-273", "50030-000", "65010-970", "69900-094", "70050-000", "80010-150"};
		
		int numSteps = 1000;
		long sleep = 100;
		
		for (int step = 0; step< numSteps; step++){
			for (int i = 0; i< ceps.length; i++){
				String cep = ceps[i];
				try {
					ViaCEPEndereco endereco = client.getEndereco(cep);
					System.out.println(endereco.getLocalidade());
					
					Thread.sleep(sleep);
				} catch (Exception e) {
					e.printStackTrace();
					System.exit(-1);
				}
			}			
		}
		
		System.out.println("BenchmarkViaCEPClient finished.");
	}
```
(Note que a instância `client` é reutilizada. Dar `new` toda vez nela pode ser um dos problemas que você está enfrentando: o client é thread-safe e pode (e deve!) ser reutilizado entre chamadas).

Se o objetivo é distribuir a lib em uma aplicação desktop ou applet, o ViaCEP Client possui ao todo 320KB (com as dependências), o que é o triplo da sua, 105KB. Mas isso é resolvível com ofuscação de código (passo que é obrigatório para Android, por exemplo), que reduz drasticamente o tamanho do arquivo final.

Sobre a idéia:

Salvar o CEP numa base para evitar a consulta novamente é o típico cenário de utilização de um cache em memória (com eventual persistência em disco, se necessário). Para tal, recomendo demais o uso do [Redis](http://redis.io/), ou se a ideia é manter tudo na VM, alguma implementação de JCache, como o [Ehcache](http://www.ehcache.org/). Em qualquer um dos casos, não sei se justificaria a criação de um projeto a mais, pois a utilização do cache seria extremamente direta (cep é a chave, o endereço é o valor), mas se achar pertinente, *just do it* ;-)

**Comment by parg-programador** [comment]
Somente explicando... Eu uso o **ViaCEP Client** em alguns projetos, mas eu fiquei responsável por um projeto onde os recursos são de uma hospedagem java compartilhada, acabei tendo que criar esse projeto por muitos pequenos problemas da hospedagem. Porém em vários outros clientes uso o **ViaCEP Client**, mas nestes casos normalmente eles possuem um ambiente cloud contratado ou um servidor interno dedicado.

Temos que nos adaptar a necessidade do cliente, fora que sempre é bom ter alternativas, eu uso o **ViaCEP Client** em mais de 10 projetos e uso o **ViaCEP** em 2, devido as necessidades e particularidades de cada um deles.

Porém eu não vejo como dois projetos com objetivos iguais, mas sim duas opções para o mesmo fim, porque cada desenvolvedor tem uma forma de pensar e programar, alguns são diretos e procuram um meio rápido e funcional para um final, enquanto outros são detalhistas e minuciosos e procuram a melhor forma para otimizar um único processo, porém ambos chegam ao produto final.

Veja o meu próprio caso, eu uso os dos projetos de acordo com a necessidade do meu cliente e dependo da necessidade eu faço em outra linguagem como PHP ou Ruby (RoR), mas a melhor coisa que existe  é a liberdade de escolha.

Eu elogio o seu projeto e reconheço que o meu ainda está em processo de amadurecimento, mas você também tem que ver que é bom para a comunidade ter opções.

Exemplo: Imagine se tivéssemos somente uma distribuição GNU/Linux, se você não gostasse teria que se adaptar a ela mesmo assim (mesmo que o seu uso seja somente em servidores), porém se eu não gostei de distros LIKE Debian eu posso usar LIKE RedHat e se eu ainda não gostei posso usar OpenSuse, todas são GNU/Linux e existe uma infinidade delas, cada uma com sua particularidade, mas isso é a grande beleza, sempre vai surgir alguém com uma nova idéia e com um jeito de pensar diferente que vai adicionar um virgula que seja, essa virgula vai agradar a gregos, mas vai desagradar troianos, mas no final das contas gregos e troianos terão feitos as suas escolhas e é isso que importa: Ter opções para poder fazer e escolhas e não ter somente uma solução para que a escolha seja feita por você.

**Comment by parg-programador** [comment]
E quanto a idéia realmente é interessante usar cache, mas eu pensei em reaproveitar os dados, por exemplo: Tabelas como Cliente, Fornecedores, Transportadores e Orçamentos, todas elas tem em comum o endereço, tirando Orçamento as outras três não existe a necessidade de duplicar o endereço no banco de dados, além de consumir recursos dificulta a vida do usuário que vai ter que atualizar esses dados e existem casos em que Clientes também são Fornecedores ou Transportadoras, portanto tem o mesmo endereço, se todos eles estão ligados a tabela CEP e eu atualizo a tabela CEP consequentemente todos estão atualizados, ainda mais se o sistema fizer isso automaticamente a cada de determinado período de tempo.

A minha idéia como um todo é melhorar um possível sistema, mas ainda não sei se vou criar o projeto ou não isso já é funcional em vários projetos que eu trabalhei.

Por enquanto é somente um ideia ter uma solução pronta para ajudar a comunidade e se eu for criar vou fazer em Java/JSP e PHP.

**Comment by gilberto-torrezan** [comment]
Não sou contra a existência de múltiplos projetos, só estou curioso para saber quais as limitações encontradas no ViaCEP Client com relação a memória - pode ser um problema grande que precisa ser resolvido o quanto antes. A existência de vários projetos para o mesmo fim, falando de comunidade open-source, é sempre bom para abrir horizontes - porém o que não acho muito legal é a falta de feedback.

**Comment by parg-programador** [comment]
Não posso entrar em detalhes por causa do contrato que eu tenho com o meu cliente, porém posso dizer que o projeto não usa o GWT e como eu disse tive problemas de memória especificamente com esse projeto ( e somente com ele ), como esse projeto já usava a **org.json** acabou que criar um novo recursos reaproveitando os já existentes melhorou a performance e o consumo de memória desse projeto (que inclusive é um cliente importante).

Com outros projetos não tive problemas. Não é um problema de memória no **ViaCEP Client**, mas sim no projeto que já estava no limite de memória da hospedagem compartilhada.

Peço desculpas se me expressei mal.
